// Code generated by gen/clog.go; DO NOT EDIT.

package format

import "github.com/quasilyte/go-ruleguard/dsl"

func ClogChainTwo(m dsl.Matcher) {
	m.Match(`$log.With().$m1($*a1).$m2($*a2).Logger()`).
		Suggest("$log.With().\n$m1($a1).\n$m2($a2).\nLogger()")
}

func ClogChainThree(m dsl.Matcher) {
	m.Match(`$log.With().$m1($*a1).$m2($*a2).$m3($*a3).Logger()`).
		Suggest("$log.With().\n$m1($a1).\n$m2($a2).\n$m3($a3).\nLogger()")
}

func ClogChainFour(m dsl.Matcher) {
	m.Match(`$log.With().$m1($*a1).$m2($*a2).$m3($*a3).$m4($*a4).Logger()`).
		Suggest("$log.With().\n$m1($a1).\n$m2($a2).\n$m3($a3).\n$m4($a4).\nLogger()")
}

func ClogChainFive(m dsl.Matcher) {
	m.Match(`$log.With().$m1($*a1).$m2($*a2).$m3($*a3).$m4($*a4).$m5($*a5).Logger()`).
		Suggest("$log.With().\n$m1($a1).\n$m2($a2).\n$m3($a3).\n$m4($a4).\n$m5($a5).\nLogger()")
}

func ClogChainSix(m dsl.Matcher) {
	m.Match(`$log.With().$m1($*a1).$m2($*a2).$m3($*a3).$m4($*a4).$m5($*a5).$m6($*a6).Logger()`).
		Suggest("$log.With().\n$m1($a1).\n$m2($a2).\n$m3($a3).\n$m4($a4).\n$m5($a5).\n$m6($a6).\nLogger()")
}

func ClogChainSeven(m dsl.Matcher) {
	m.Match(`$log.With().$m1($*a1).$m2($*a2).$m3($*a3).$m4($*a4).$m5($*a5).$m6($*a6).$m7($*a7).Logger()`).
		Suggest("$log.With().\n$m1($a1).\n$m2($a2).\n$m3($a3).\n$m4($a4).\n$m5($a5).\n$m6($a6).\n$m7($a7).\nLogger()")
}

func ClogChainEight(m dsl.Matcher) {
	m.Match(`$log.With().$m1($*a1).$m2($*a2).$m3($*a3).$m4($*a4).$m5($*a5).$m6($*a6).$m7($*a7).$m8($*a8).Logger()`).
		Suggest("$log.With().\n$m1($a1).\n$m2($a2).\n$m3($a3).\n$m4($a4).\n$m5($a5).\n$m6($a6).\n$m7($a7).\n$m8($a8).\nLogger()")
}
